# Generated by Django 3.1.4 on 2020-12-28 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='timestamp',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
